# development:
#   stripe_secret_key: <%= ENV['STRIPE_SECRET_KEY'] %>
#   stripe_publishable_key: <%= ENV['STRIPE_PUBLISHABLE_KEY'] %>
# # production:
#   # stripe_secret_key: 'sk_live_aLvPhyGtUwlLSHvms3KhCdrL'
#   # stripe_publishable_key: 'pk_live_nbTqsm8Gg0eHGrQVRbWnjlyN'

  
 